---
title: "Workshop 3 Instructions"
subtitle: "Interactive Plots and Web Publishing with Quarto"
author: "The GRAPH Courses Team"
output: prettydoc::html_pretty
---

# Intro

In this workshop, you will replicate a specific Our World in Data (OWID) page featuring data on self-reported life satisfaction from the Gallup World Poll.

The goal is to use R and Quarto to recreate the interactive tables and charts found here: [https://ourworldindata.org/grapher/happiness-cantril-ladder](https://ourworldindata.org/grapher/happiness-cantril-ladder){target="_blank"}. You will then generate an HTML output file and publish it online using GitHub Pages.

An example of the completed HTML page for this workshop can be viewed [here](https://the-graph-courses.github.io/rmc_life_satisfaction_webpage/){target="_blank"}.

# Instructions

1.  Fork the workshop repo here: [https://github.com/the-graph-courses/rmc_life_satisfaction_webpage](https://github.com/the-graph-courses/rmc_life_satisfaction_webpage){target="_blank"}. This step should be completed in your web browser.
2.  Clone to your local computer.
3.  Open the project file (`rmc_03_workshop.Rproj`) in RStudio.
4.  In your Files pane, open the `index.qmd` file, and replace the `"WRITE_YOUR_CODE_HERE"` chunks with your answers.
5.  If you finish early, try the optional challenge section which is at the bottom of the file.
6.  **Add tabsets.** We covered this in prework but you can review it [here](https://quarto.org/docs/output-formats/html-basics.html#tabsets){target="_blank"}.
7.  When finished, render your HTML, push your changes to GitHub and enable GitHub Pages for the repository. 
